# Generated by Django 4.2 on 2023-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('cnic_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('age_years', models.IntegerField()),
                ('age_months', models.IntegerField()),
                ('age_days', models.IntegerField()),
            ],
        ),
    ]
