# Generated by Django 4.2 on 2023-05-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_alter_patient_age_days_alter_patient_age_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('pannel_case', models.BooleanField()),
                ('pannel_emp_id', models.CharField(max_length=100)),
                ('referred_by', models.CharField(max_length=100)),
                ('collected_by', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('special_refer', models.CharField(max_length=100)),
                ('phlebotomist', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concession', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pannel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.patient')),
            ],
        ),
    ]
