# Generated by Django 4.2 on 2023-06-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0005_parameters_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
