# Generated by Django 4.2 on 2023-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0006_accountentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('admin', 'Admin'), ('pathologist', 'Pathologist'), ('receptionist', 'Receptionist'), ('clerk', 'Clerk')], max_length=50)),
            ],
        ),
    ]
