# Generated by Django 4.2 on 2023-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0007_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_unit', models.CharField(max_length=50)),
                ('parameter_result_type', models.CharField(max_length=50)),
            ],
        ),
    ]
