# Generated by Django 4.2.3 on 2023-07-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0009_rangeparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_duration', models.CharField(max_length=50)),
                ('test_department', models.CharField(max_length=100)),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.parameter')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.test')),
            ],
        ),
    ]
