# Generated by Django 4.2.3 on 2023-07-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0011_labregistration_labitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labregistration',
            name='pannel_case',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='labregistration',
            name='self',
            field=models.IntegerField(),
        ),
    ]
