# Generated by Django 4.2.3 on 2023-07-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0012_alter_labregistration_pannel_case_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabItems',
        ),
        migrations.DeleteModel(
            name='LabRegistration',
        ),
    ]
