# Generated by Django 4.2.3 on 2023-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0015_alter_labregistration_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labregistration',
            name='pannel_case',
            field=models.CharField(max_length=100),
        ),
    ]
