# Generated by Django 4.2.3 on 2023-07-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0016_alter_labregistration_pannel_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labregistration',
            old_name='self',
            new_name='relation',
        ),
    ]
