# Generated by Django 4.2.3 on 2023-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0017_rename_self_labregistration_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='labitems',
            name='labitem_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='lab_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
