# Generated by Django 4.2.3 on 2023-08-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0018_labitems_labitem_status_labregistration_lab_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('lab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.labitems')),
            ],
        ),
    ]
