# Generated by Django 4.2.3 on 2023-08-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0020_result_resultitems_delete_labitemresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitems',
            name='remarks',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
