# Generated by Django 4.2.3 on 2023-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0021_resultitems_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultitems',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultitems',
            name='result_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultitems',
            name='type_normal_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultitems',
            name='values',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
