# Generated by Django 4.2.3 on 2023-09-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0022_alter_resultitems_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitems',
            name='parameterName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
